create table pacotesviagem (id_pacotes int8 generated by default as identity, destino varchar(255), origem varchar(255), preco float4 not null, primary key (id_pacotes));
create table pacotesviagem (id_pacotes int8 generated by default as identity, destino varchar(255), origem varchar(255), preco float4 not null, primary key (id_pacotes));
create table pacotesviagem (id_pacotes int8 generated by default as identity, destino varchar(255), origem varchar(255), preco float4 not null, primary key (id_pacotes));
create table pacotesviagem (id_pacotes int8 generated by default as identity, destino varchar(255), origem varchar(255), preco float4 not null, primary key (id_pacotes));
